// Code generated by gen_redis_cmd. DO NOT EDIT.

package redis

func init() {
	implementedCommands["hdel"] = hDel
	implementedCommands["hexists"] = hExists
	implementedCommands["hget"] = hGet
	implementedCommands["hgetall"] = hGetAll
	implementedCommands["hincrby"] = hIncrBy
	implementedCommands["hincrbyfloat"] = hIncrByFloat
	implementedCommands["hkeys"] = hKeys
	implementedCommands["hlen"] = hLen
	implementedCommands["hmget"] = hMGet
	implementedCommands["hmset"] = hMSet
	implementedCommands["hset"] = hSet
	implementedCommands["hsetnx"] = hSetNx
	implementedCommands["hvals"] = hVals
}
