// Code generated by gen_redis_cmd. DO NOT EDIT.

package redis

func init() {
	implementedCommands["keys"] = keys
	implementedCommands["exists"] = exists
	implementedCommands["del"] = del
	implementedCommands["type"] = keyType
	implementedCommands["ping"] = ping
	implementedCommands["command"] = command
}
