// Code generated by gen_redis_cmd. DO NOT EDIT.

package redis

func init() {
	implementedCommands["lpush"] = lPush
	implementedCommands["lpop"] = lPop
	implementedCommands["rpush"] = rPush
	implementedCommands["rpop"] = rPop
	implementedCommands["llen"] = lLen
	implementedCommands["lrange"] = lRange
	implementedCommands["lrem"] = lRem
	implementedCommands["lindex"] = lIndex
	implementedCommands["lset"] = lSet
	implementedCommands["linsert"] = lInsert
}
