// Code generated by gen_redis_cmd. DO NOT EDIT.

package redis

func init() {
	implementedCommands["sadd"] = sAdd
	implementedCommands["scard"] = sCard
	implementedCommands["sdiff"] = sDiff
	implementedCommands["sdiffstore"] = sDiffStore
	implementedCommands["sinter"] = sInter
	implementedCommands["sinterstore"] = sInterStore
	implementedCommands["sunion"] = sUnion
	implementedCommands["sunionstore"] = sUnionStore
	implementedCommands["sismember"] = sIsMember
	implementedCommands["smembers"] = sMembers
	implementedCommands["smove"] = sMove
	implementedCommands["srem"] = sRem
	implementedCommands["spop"] = SPop
}
