// Code generated by gen_redis_cmd. DO NOT EDIT.

package redis

func init() {
	implementedCommands["zadd"] = zAdd
	implementedCommands["zscore"] = zScore
	implementedCommands["zrank"] = zRank
	implementedCommands["zrem"] = zRem
	implementedCommands["zcard"] = zCard
	implementedCommands["zcount"] = zCount
	implementedCommands["zincr"] = zIncr
	implementedCommands["zrange"] = zRange
	implementedCommands["zrangebyscore"] = zRangeByScore
	implementedCommands["zrevrange"] = zRevRange
}
