// Code generated by gen_redis_cmd. DO NOT EDIT.

package redis

func init() {
	implementedCommands["set"] = set
	implementedCommands["get"] = get
	implementedCommands["mget"] = mget
	implementedCommands["incr"] = incr
	implementedCommands["incrby"] = incrBy
	implementedCommands["decr"] = decr
	implementedCommands["decrby"] = decrBy
	implementedCommands["append"] = stringAppend
}
