name: Go

on:
  push:
    branches: [ master, dev]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 go build -v ./...

    - name: Test
      run: CGO_ENABLED=0 go test -v ./...
